export * from './mecanico.model';
export * from './persona.model';
export * from './propietario.model';
export * from './jefe-operaciones.model';
export * from './vehiculo.model';
export * from './seguro.model';
export * from './revision-niveles.model';
export * from './cambio-repuesto.model';
export * from './repuesto.model';
